trigger:
- master

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: TJ_Sub1(43498770-9565-4b71-bbe5-ba85a11c7827)
  resourceGroupName: 'exampleRG'
  location: '<your-resource-group-location>'
  templateFile: BIcep/Templates/Appservice/Main.bicep
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)